### ISSUE TITLE
Multiple Versions Created Upon Pool Creation (Bug)

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/archives#1]
I don't know if this is a one-off error or something else, but I noticed the following when browsing through the [pool versions](http://danbooru.donmai.us/pool_versions).

http://danbooru.donmai.us/pool_versions?search%5Bpool_id%5D=12054

It basically created 5 versions for 5 different pool adds done at pool creation.

**Comment by evazion** [comment]
Merging of versions was disabled in 39a6d69e3c3652a92cc88c9738baa523affe1aa9 so I guess it's intentional?

**Comment by r888888888** [comment]
Yeah, it was causing headaches so I just disabled it. Although the desc_changed flag seems bugged.
