### ISSUE TITLE
Process.daemon redirects all output to /dev/null by default

### ISSUE THREAD

**Issue by Type-kun** [r888888888/archives#5]
When no arguments are specified, `Process.daemon` redirects all output to `/dev/null`; therefore, if the service is run directly via `bundle exec ruby services/sqs_processor.rb --logfile=my.log --pidfile=my.pid`, no output is logged. After changing the line to `Process.daemon(true, true)`, it executes fine and logs output as expected.

Disclaimer: I have no idea what sets the `RUN` environment variable, because googling that turned out quite difficult.

**Comment by r888888888** [comment]
RUN is something you would set when you don't want it to detach. There's an example of its usage in the Procfile.

**Comment by Type-kun** [comment]
Keep in mind that setting the arguments as (nil, true) will make the script change its working dir to `/`, and attempt to create log and pid files there. This would fail unless you run it as root or have write permission on `/`, or specify the full path for log and pid files. Setting the arguments as (true, true) will make the script stay in the same directory.
